pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ACCOUNT_ID = "801195563235"
        ECR_REPO = "auth-service"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Kavin9898/netflix-production.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'chmod +x ci-cd/docker-build.sh'
                sh './ci-cd/docker-build.sh'
            }
        }

        stage('Deploy to ECS') {
            steps {
                sh 'chmod +x ci-cd/deploy.sh'
                sh './ci-cd/deploy.sh'
            }
        }
    }
}